### ISSUE TITLE
AttributeError: 'module' object has no attribute '__path__' with Django 1.6

### ISSUE THREAD

**Issue by Karmak23** [Suor/django-pickling#2]
Hi,

I tried installing `django-pickling` on my Django 1.6 setup (Python 2.7.9), following the advise in `cacheops` performance tips. 

Adding it to `INSTALLED_APPS` results in this stacktrace: 

```
10:55:44 web.1  | Traceback (most recent call last):
10:55:44 web.1  |   File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
10:55:44 web.1  |     self.result = application(self.environ, self.start_response)
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
10:55:44 web.1  |     return self.application(environ, start_response)
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
10:55:44 web.1  |     self.load_middleware()
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
10:55:44 web.1  |     mw_instance = mw_class()
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
10:55:44 web.1  |     for url_pattern in get_resolver(None).url_patterns:
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
10:55:44 web.1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
10:55:44 web.1  |     self._urlconf_module = import_module(self.urlconf_name)
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
10:55:44 web.1  |     __import__(name)
10:55:44 web.1  |   File "/home/olive/sources/1flow/oneflow/urls.py", line 66, in <module>
10:55:44 web.1  |     url(r'^djangojs/', include('djangojs.urls')),
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
10:55:44 web.1  |     urlconf_module = import_module(urlconf_module)
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
10:55:44 web.1  |     __import__(name)
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/src/django.js/djangojs/urls.py", line 36, in <module>
10:55:44 web.1  |     url(r'^translation$', 'django.views.i18n.javascript_catalog', js_info_dict(), name='js_catalog'),
10:55:44 web.1  |   File "/home/olive/.virtualenvs/1flow/src/django.js/djangojs/urls.py", line 25, in js_info_dict
10:55:44 web.1  |     for path in module.__path__:
10:55:44 web.1  | AttributeError: 'module' object has no attribute '__path__'
10:55:44 web.1  | [06/Feb/2015 10:55:44] "GET / HTTP/1.1" 500 59
```
Removing it from `INSTALLED_APPS` solves the crash so I assume it comes from this package, but I don't have a detailled stacktrace for this crash.

Looking at available stacktraces, I found [this one](http://dev.1flow.net/development/1flow-dev/group/51928/) that could imply an interaction problem with `django-position` and is probably different than the current one which just prevents the webserver from handling any request.  

The whole setup — and other interacting apps — is quite complex, but it's [here](https://github.com/1flow/1flow/blob/develop/oneflow/settings/snippets/common.py) if you dare looking at it ;-) 

Do you have any hint of what could be causing this strange problem ?

Thanks & best regards,

**Comment by Suor** [comment]
It's an error in `djangojs/urls.py` line 25. It assumes module has `__path__` attribute, but this is only true if module is a package and `django_pickling` is just a single file. It has however `__file__` set, so this will work:
```python
import os.path
os.path.dirname(module.__file__)
```

**Comment by Karmak23** [comment]
OK thanks. I will report the bug to Django-js.
